### ISSUE TITLE
npm is required for publishing/execution of policy packs

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-policy#102]
`@pulumi/policy` should mostly operate transparently and "magically." A `pulumi up` or a `pulumi preview` should retrieve from the backend the set of policy packs that an administrator has mandated for the organization, and do whatever preparation needs to be done, and then boot them so they can receive resource definitions for validation against policy. In other words, policy authors should write and publish policies; infrastructure developers should simply run `pulumi up` and get notified of policy violations.

One wrinkle in this vision is that policy packs are "real" programs—and therefore must run `npm install` to get dependencies before they can be booted and hooked up to the engine. The reason for this (in the case of node) is that `node_modules` is not a completely self-contained set of things required to run a node program—for example, gRPC requires several system components to be installed by the `{npm|yarn} install` post-install hooks.

There are several ways in which this is leaky, but one of the more painful ones right now is: not all users use `npm`, and we don't have a way of customizing what to do instead.

There are several alternatives:

* Allow `Pulumi.yaml` (or whatever file we end up using instead) to have a field like `install-script: yarn install` which allows policy authors to change this.
* Allow this to be configured via env variables.
* Remove the need to do install at all, somehow. (Not clear how?)

One complication is that this layer can't be completely naive about this implementation detail. We have to intercept errors when this step fails and put them into the output, so the user knows what happened. So it seems like we'll have to manually curate package managers for users, and bake them directly into Pulumi, at least in the near term.

**Comment by hausdorff** [comment]
I should also note that this is a problem also, though to a lesser extent, with the `policy publish` subcommand. It uses `npm pack` directly. So the right thing to do here might to be to have the administrator decide which package manager to use explicitly require a config variable for the package manager to use, which would require them to set it prior to `policy publish`. Then, we can re-use that choice for policy execution as well.

**Comment by justinvp** [comment]
Moving this to next milestone to make room for wrapping up the higher priority items this milestone.
