### ISSUE TITLE
Improved Getting Started experience

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi-policy#104]
The readme currently suggests you go `cd sdk/nodejs/policy/examples/aws` to get started writing a Policy Pack. I think we should improve this experience by letting authors create a new Policy Pack using the CLI or at least have instructions on how to start a pack from scratch.

**Comment by ekrengel** [comment]
Created this doc -- https://docs.google.com/document/d/1tAsssk8UTjvneIWwK85wiqoMBKwjieiTbWQpKqoPQpE/edit

Hoping someone will review it.. maybe @clstokes or @lukehoban ?

**Comment by lukehoban** [comment]
Left review feedback in the doc above.

**Comment by lukehoban** [comment]
Initial doc is written and reviewed - pushing remaining follow-ups to M28.  

Moving this content into actual www.pulumi.com/docs docs and expanding coverage will be useful.

**Comment by ekrengel** [comment]
Going to close this out for now since the basic doc is done. Will open separate issues for the expanded docs / examples we will do this Q.
