### ISSUE TITLE
Policy SDK to allow you to aggregate resources

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi-policy#105]
Per Cameron:

Can I aggregate data across rule executions?

And really what I'm getting at is, can I do a cost estimation of a pulumi stack? Effectively, count the t3.mediums in a stack, multiply by $0.0X, and then print a warning if the sum is greater than $XX?

**Comment by joeduffy** [comment]
Also to keep in mind:

There are also rules that may need to analyze multiple different kinds of resources (e.g. inspect the DNS records for a route53 zone, load balancers for a given EC2 server, etc)

**Comment by gpduck** [comment]
I'd like to be able to make a policy for Azure that checks to make sure a DiagnosticSetting resource was provisioned (and attached) if a KeyVault is provisioned.  Something that might look like this:

**Stack Definition (simplified):**

```
const kv = new azure.keyvault.KeyVault('kv', {});

const diag = new azure.monitor.DiagnosticSetting('diag', {
    targetResourceId: kv.id
});
```

**Policy:**

```
{
    name: 'KeyVault diagnostic settings',
    description: 'All KeyVaults must have diagnostic settings forwarded to security event hub',
    enforcementLevel: 'mandatory',
    rules: [
        stackRule( stack => {
            stack.resources.filter( r => {
                azure.keyvault.KeyVault.isInstance(r)
            }).forEach( kv => {
                assert(stack.resources.some( r => {
                    azure.monitoring.DiagnosticSetting.isInstance(r) && r.targetResourceId == kv.id
                }))
            })
       })
    ]
}
```

**Comment by justinvp** [comment]
The PR to hook this up to the new API is #135, but I ran into a couple design issues that need to be addressed before we can merge it.
