### ISSUE TITLE
Improve messaging on "Remove stack" option

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/pulumi-policy#107]
![Screenshot from 2019-09-13 13-40-28](https://user-images.githubusercontent.com/5844484/64893563-3655ab80-d62c-11e9-9a40-a9710c4b26d9.png)

Make the confirmation prompt clearer that the stack removal is within the context of the Policy Group. We can maybe make the font smaller, then have something like:

```
Remove stack from this policy group?

This will remove <stack-name> from <policy-group-name>.
```

**Comment by ekrengel** [comment]
Since I am using a generic confirmation dialog, its harder than its worth to change font size here. I have simply added "from Policy Group" to the end of the message. Hopefully this will make it clear enough!
