### ISSUE TITLE
There are many names fields for Policy Packs

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi-policy#109]
We have many places where we require users to type a name:

1. The pulumi yaml file
1. publishing a Policy Pack via the CLI
1. package.json
1. The typescript object

```
new PolicyPack("policy-pack-typescript", {
   ....
});
```

Can we somehow simplify this? They're interaction is unclear and confusing.

**Comment by justinvp** [comment]
Related to #38

**Comment by justinvp** [comment]
@ekrengel, @clstokes, do you have a preference?

I'm leaning towards only using the name specified in `PulumiPolicy.yaml`, which aligns with where projects are named for Pulumi programs (in `Pulumi.yaml`).

Other places:

## publishing a Policy Pack via the CLI
   
The downside is this forces you to always remember and type the policy pack name when doing a publish/apply.

As an aside, as a future improvement idea, it'd be nice if running `pulumi policy publish` without any args prompted you to select the organization to publish to. If we were setting the name via the CLI we could also prompt to use any existing policy pack names in the organization (or create a new name). But we'd have to implement the service APIs and wire it all up with the CLI to enable such an experience.

## package.json

We don't use this at all for Pulumi programs, so I don't think we should do anything different for Policy Packs.

 It does need to be there to make npm happy, but for most policy packs, it could be a generic name like what we do with all our project templates in https://github.com/pulumi/templates. Of course, if you are creating a general purpose package that you plan to publish to npm, you'll want to specify an appropriate name in package.json, but as far as Pulumi is concerned, we don't look at it.

## The typescript object

This would align with how we name resources in Pulumi programs, but the project and stack names aren't specified in code, so I'm leaning towards not doing it here for policy packs.

However, we also don't have `new Project("myproject", { resources: [ ... ] })` for Pulumi programs like the equivalent `new PolicyPack("mypack", { policies: [ ... ] })` for Policy Packs, and our current plan for configuring policies is to just configure those in code (for now), so I could be convinced that it'd make sense to specify the policy pack name in code as well (the same place other things are being configured/specified). Then `PulumiPolicy.yaml` would just be relegated to specifying the runtime (e.g. node vs python vs other) and other associated details the CLI needs to run the policy pack.

**Comment by ekrengel** [comment]
The confusing thing about putting it in the `PulumiPolicy.yaml` file is that its not quite 1:1 with how we handle stacks. I see a Policy Pack name semi-equivalent to the stack name, but the project name. The other thing is that this file is a bit "obscured" -- meaning it makes it a bit harder to figure out where the name of the Policy Pack is coming from.

I think my preference is the typescript object because its very clear and easy to see.

**Comment by justinvp** [comment]
> I think my preference is the typescript object because its very clear and easy to see.

You convinced me. Let's go with that :)

**Comment by justinvp** [comment]
WIP/hacky version at https://github.com/pulumi/pulumi/tree/justin/policy_name. Will finish getting this into shape today.
