### ISSUE TITLE
Expose `ComponentResourceOptions` in policy rules

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#110]
Policies should be able to access and check values from the `ComponentResourceOptions` object on resources. This would allow checking of `protect`, `additionalSecretOutputs`, and more for critical resource types.

**Comment by justinvp** [comment]
Related: https://github.com/pulumi/pulumi/pull/3554 and https://github.com/pulumi/pulumi-policy/pull/151 add the resource URN and name. I'll be looking at resource options next.

**Comment by justinvp** [comment]
Part of this includes exposing the `parent`.

**Comment by justinvp** [comment]
PRs are here:
- https://github.com/pulumi/pulumi/pull/3720
- https://github.com/pulumi/pulumi-policy/pull/172

There are some minor design points that need to be finalized; moving to M31 and will close in the next day or two.
