### ISSUE TITLE
Support custom assertion message

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi-policy#112]
We should be printing the custom assertion message in the `assert`.

For example if I used the below rule and it failed, I would expect "Are you sure you want to use an xlarge instance?" to be printed.
```
rules: [
            typedRule(aws.ec2.Instance.isInstance, it => {
                assert(!it.instanceType.includes("xlarge"),
                    "Are you sure you want to use an xlarge instance?");
            }),
        ],
```

Talking to @hausdorff it is expected that this does work, so we may have some regression here.

**Comment by hausdorff** [comment]
This should definitely already work. Let's fix this week.
