### ISSUE TITLE
Add a --dir flag for pulumi policy publish command

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/pulumi-policy#114]
Right now, it's not very clear that org owners have to run `pulumi policy publish` in the policy pack directory. It will be nice to have a `--dir` flag that users can pass as an option.

**Comment by justinvp** [comment]
The CLI already has a global `--cwd`/`-C` flag that can be used to do this, e.g.:

```sh
pulumi policy publish --cwd path-to-policy-pack-dir
```
