### ISSUE TITLE
Policy still requires Policy.yaml in addition to PolicyPack.yaml

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#128]
Pulumi `v1.3.1` changed to require `PulumiPolicy.yaml` for policy packs, but still seems to require `Pulumi.yaml` in the policy pack too.

I can publish the policy pack with just `PulumiPolicy.yaml` present, but when I apply the pack and then `pulumi up` with it applied I get an error.

```
clstokes@Camerons-MBP aws-ts-webserver % pulumi up
Previewing update (dev):
Downloading policy pack
Unpacking policy zip "/Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v38.tmp309720071" "/Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v38"
error: failed to load policy project at /Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v38: open /Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v38/Pulumi.yaml: no such file or directory
clstokes@Camerons-MBP aws-ts-webserver %
```

If I `cp PulumiPolicy.yaml Pulumi.yaml` in the policy pack, publish, and apply, and then `up` it works again.

**Comment by justinvp** [comment]
From a quick look, the issue appears to be (but will need to debug in more detail):

https://github.com/pulumi/pulumi/blob/730fe8617e8355d6ef7e49b1d29a23845baf1e0b/pkg/backend/httpstate/policypack.go#L207-L210
