### ISSUE TITLE
Output no longer display the Policy name

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi-policy#136]
The Policy violation use to include the policy name. This is no longer the case. I had found this useful for referencing which Policy was the one failing.

Current behavior:
```sh
  aws:ec2:Instance (test-ec2-instance):
                mandatory: ECS instance's EBS volume (undefined) must be marked for termination on delete.
```

Previously the policy name was included like this. It doesnt necessarily need to be this exact display, but ya get the point.
```sh
  aws:ec2:Instance (test-ec2-instance):
                mandatory: [my-awesome-policy-name] ECS instance's EBS volume (undefined) must be marked for termination on delete.
```

**Comment by justinvp** [comment]
@ekrengel, you wouldn't happen to know what version of pulumi CLI and `@pulumi/policy` used to print the policy name? Just trying to understand when/where this changed.

**Comment by ekrengel** [comment]
@justinvp I am not sure.. but I think this is the code that use to do it [server.ts](https://github.com/pulumi/pulumi-policy/pull/113/files)
