### ISSUE TITLE
Analysis of dependencies of a resource

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-policy#162]
While checking policy for a resource, I want a simple way to inspect resources that my resource depends on. Example:

1. Policy "Azure Function Apps" should run on Consumption Plan.
2. I should inspect every Function App, use its `appServicePlanId` to somehow get the Plan resource, and check its type.
3. I can't simply prohibit the creation of a Plan of a wrong type: they might be needed for App Service resources.
4. Plan is always created before Function App, because there is a direct dependency there. However, Plan could be an external resource for the current stack.

A resource policy can't currently do that.

A stack policy usually can, but it won't prevent the resource creation. Also, the API is currently less intuitive. Also, how do I navigate around the item (4) in this case?

Unfortunately, I don't have a good suggestion right now. I'm logging this issue to track possible ideas.

**Comment by ekrengel** [comment]
May need to consolidate with https://github.com/pulumi/pulumi-policy/issues/153 -- justin to evaluate
