### ISSUE TITLE
Clarify in docs how secrets are handled in policies

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-policy#163]
Follow up to #30, related #115

Policies currently have unrestricted access to secrets. If I set my `SqlServer.administratorLoginPassword` to a secret value in a Pulumi program, every policy would get it as plain text with no indication of its secretness.

In an ideal case, IMO:

1. Secret values would be clearly marked as secrets.
2. Policy code could still get their values if needed.
3. Exposing the values in validation errors and other strings would require an explicit action, e.g. calling a function to "decode" it.
4. There could also be an opt-in flag to unmask all secrets for a policy so that by default the values are all dummy "[secret]", but this can be disabled when needed.

I guess my intention is to make this secure by default and transparently turned off when secret values need to be dealt with.

**Comment by ekrengel** [comment]
Clarify in docs whats going on.

**Comment by justinvp** [comment]
Will take care of clarifying this in the docs early next week.
