### ISSUE TITLE
Implement SDK for configuration

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi-policy#175]
Related to: https://github.com/pulumi/pulumi-policy/issues/91

- Implement SDK
- Add calls in CLI needed to send / consume configuration

Do we need to bump min version for Policy?

**Comment by ekrengel** [comment]
I believe @justinvp is planning on breaking this up into smaller tasks, but this is a placeholder for now. I suspect those smaller tasks will get divided amongst all 3 of us (jamie, justin, erin)

**Comment by justinvp** [comment]
Here's a breakdown of the work. Some of these may be done together at the same time as we bootstrap things.

@ekrengel, @jkisk, any feedback before I open issues for each top-level bullet?

* Add `--policy-pack-config` flag to commands that accept `--policy-pack`
	* Specifies path to a JSON file containing the config for a policy pack
	* The `--policy-pack` and `policy-pack-config` flags are order-dependent. e.g. the very first `--policy-pack-config` flag value corresponds to the very first `--policy-pack` flag value. And so on for the second, third, etc. (And we emit an error if you specify `--policy-pack-config` and you don’t specify a `--policy-pack-config` flag for every `--policy-pack` that was set.)
* Pass config to Policy Pack plugin
	* Validate and determine any errors (emitting all errors up-front) before passing to the policy pack
	* Fill in default values from schema for any missing values before passing config to the policy pack
* Add object model API to declare schema in `@pulumi/policy` 
* Add object model API for accessing config from policy validation handlers in `@pulumi/policy` 
* Send config schema to service
	* Return schema as part of policy pack's metadata
	* Send to service as part of sending other metadata
* Use config from the service for required policy packs
* Make `all` a reserved policy name
	* Reserve this name for configuring “all” policies so that policy pack authors cannot use it
* Add top-level `enforcementLevel` to `PolicyPackArgs`
	* Change `enforcementLevel` on each policy to be optional 
* Update AWSGuard to use new config model
	* As part of this, consider consolidating any utility/helper code in `@pulumi/policy` to make it easy to author other Policy Packs in a similar manner

**Comment by ekrengel** [comment]
I think this probably covers all the basis, though probably not in the correct order?

Questions:

> Add object model API to declare schema in `@pulumi/policy` 

Did we want to do this a protobuf in pulumi/pulumi so that we dont have to keep recreating the model?

How does this factor into us wanting to support OPA?

**Comment by justinvp** [comment]
> I think this probably covers all the basis, though probably not in the correct order?

Yeah, order is not necessarily right. There are also some chicken-and-egg problems for some of these, that we'll probably want to do at the same time.

> Did we want to do this a protobuf in pulumi/pulumi so that we dont have to keep recreating the model?

Is your suggestion to define the object model using protocol buffers (`.proto` file) and then codegen the definitions in each language? That might help, but might be more moving parts than it's worth. I think the object model for these will be relatively simple, so the duplication in each language won't be too bad.

> How does this factor into us wanting to support OPA?

This is a good question. We should have an issue around how config gets passed to OPA-based policies.

**Comment by ekrengel** [comment]
@justinvp reasigning to you bc youve been doing this work.. please close if this is a duplicate. We originally opened this as a placeholder, but I believe you have opened smaller issues in its place.

**Comment by justinvp** [comment]
I'm going to close this as all the work is tracked in smaller issues.
