### ISSUE TITLE
Remove the need to set `PULUMI_EXPERIMENTAL` to use policy CLI commands

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-policy#196]
Before GA, we should remove the need to set the `PULUMI_EXPERIMENTAL` env variable to use policy commands.

**Comment by joeduffy** [comment]
I actually didn't realize we already put `[PREVIEW]` indicators on some commands in the CLI:

![image](https://user-images.githubusercontent.com/3953235/74201108-9d987b80-4c1d-11ea-81e0-765bacda3a33.png)

I'd vote for doing that change to the `policy` subcommand immediately.

**Comment by justinvp** [comment]
Dupe. We'll use https://github.com/pulumi/pulumi/issues/3985 to track this work.
