### ISSUE TITLE
Python: Support publishing Python policy packs

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-policy#211]
- [ ] Return actual policy pack version
- [ ] Package and publish Python policy packs
- [ ] Download, install dependencies, and use Python Policy Packs from the service

**Comment by ekrengel** [comment]
Is there anything that needs to be done server side of this? I don't think so, but just wanted to confirm / get it in our backlog if so.

**Comment by justinvp** [comment]
> Is there anything that needs to be done server side of this? I don't think so, but just wanted to confirm / get it in our backlog if so.

I don't think so... The service doesn't care about the bytes in the package that gets uploaded, right? As far as the service is concerned, it's just an opaque package of bytes, right?

**Comment by ekrengel** [comment]
>  it's just an opaque package of bytes, right?

correct!
