### ISSUE TITLE
Policy pack path should be relative to the pulumi command and not the pulumi project

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-policy#251]
In a directory structure like:
```
./workspace
|- infrastructure
|- infra-policy
```

I would expect to be able to run:
```
pulumi -C infrastructure --policy-pack infra-policy
```

But currently, the policy pack is relative to the project, so one must specify:
```
pulumi -C infrastructure --policy-pack ../infra-policy
```

**Comment by lukehoban** [comment]
The help text for `—cwd` says: “ Run pulumi as if it had been started in another directory”, which might suggest this is by design?  Honestly not sure. 

I assume we have other flags that take paths - is this a universal behavior for `—cwd`?

**Comment by leezen** [comment]
Yes, it seems to be universal behavior. Another example is `stack export -f` where the file also ends up in a location relative to the project. I guess I'll close this as "by design."
