### ISSUE TITLE
Policypack does not multiple import

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-policy#269]
Hi,
I would like to separate policypack in multiple files.
I have create the following example: [bug.zip](https://github.com/pulumi/pulumi-policy/files/6656490/bug.zip)
```
├── __main__.py
├── policypack
│   ├── advisory.py
│   ├── __main__.py
│   ├── mandatory.py
│   └── PulumiPolicy.yaml
└── Pulumi.yaml
```

## Steps to reproduce

1. `pulumi preview --policy-pack policypack`

Expected: Both policypack (`advisory.py` and `mandatory.py`) are run
Actual: only the first in the list of `import` is run:
```
$ pulumi preview --policy-pack policypack
Previewing update (dev):
     Type                         Name            Plan       Info
 +   pulumi:pulumi:Stack          cyclecloud-dev  create     3 messages
 +   └─ azure:core:ResourceGroup  jump_rg         create

Diagnostics:
  pulumi:pulumi:Stack (cyclecloud-dev):
    POL1
    POL1
    POL1
```

Am I misunderstanding the use of policypack?

Thanks

**Comment by leezen** [comment]
I believe that there should only be a single `PolicyPack` object created for each policy pack. I see there are two being created in your example. /cc @justinvp to confirm that this is the expectation.

**Comment by justinvp** [comment]
> I believe that there should only be a single `PolicyPack` object created for each policy pack.

Yes, that's right. You can have separate `ResourceValidationPolicy` or `StackValidationPolicy` objects defined in separate files, but they'd need to be combined into a single `PolicyPack` object.

**Comment by yellowhat** [comment]
Ok. Thanks.
