### ISSUE TITLE
No Java Examples for CrossGuard

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-policy#284]
https://www.pulumi.com/docs/guides/crossguard/
https://github.com/pulumi/pulumi-policy

None of the above places we see pulumi crossguard examples, pl. do add java examples.

**Comment by stack72** [comment]
Hi @nagkumar 

Policies are only available to be written in TypeScript / JavaScript / Python. There is no support for writing policies in Java at this time

Paul
