### ISSUE TITLE
Idea: Add flag to apply immediately during publish

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#29]
The current workflow of running `... publish` and then `... apply` is a little cumbersome when done manually (copy/paste of the version number that's returned) and will require some extra "logic" when done in a CD tool (capturing the output to use in the next command).

Could we add a `--apply` (or similarly named) flag to the `publish` command to apply the newly published package immediately?

**Comment by ekrengel** [comment]
Closing since now we have policy groups
