### ISSUE TITLE
Decide how to handle secrets in `Analyze`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-policy#30]
Following up from https://github.com/pulumi/pulumi/pull/2955, we should decide explicitly how we want to handle secrets. This PR makes no attempt to do this.

**Comment by hausdorff** [comment]
@lukehoban how important is this for beta v2? Should we try to solve this week?

**Comment by lukehoban** [comment]
This feels like a correctness requirement - else things will just occasionally fail.  I’d suggest we should address (or at the very least come up with a plan we feel good about).
