### ISSUE TITLE
Remove display name

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-policy#33]
Following up from this issue: https://github.com/pulumi/pulumi-policy/pull/21#discussion_r305146970

I think we should remove `displayName` from the PaC policy model, and just use `name` and `description` instead. See discussion below.

> is there a way we can generate these names for users from a display name? Or are we forgoing to the display name?

> We can generate IDs from display names, but I personally think we should just get rid of the display name field—I think it's unlikely that having a dedicated "display name" field that separate from ID will increase clarity or decrease complexity:
> 
> * Users are already used to providing "user readable" IDs to all Pulumi `CustomResource` classes, and that seems to work ok.
> * AWS [config rules](https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html) don't have display names, and that seems to work ok too ([_cf_](https://docs.aws.amazon.com/config/latest/developerguide/lambda-function-settings-check.html).).
> * If IDs are generated from display names, that just means that the display names have to be unique instead of the IDs—effectively making the display name the unique ID. And if that's true, why not just eliminate the ID field altogether?

cc @ekrengel

**Comment by justinvp** [comment]
We've already removed display name.
