### ISSUE TITLE
Allow use of pulumi.getStack() from a rule

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#42]
We should allow the use of `pulumi.getStack()` and other engine things from within rules (such as data sources and reads - `.get(...)`'s). This will enable rules such as `an instance's Name tag must end with the stack name`. Attempting to use `pulumi.getStack()` from a rule currently throws an error (or seems to as the rule fails but without a specific error message).

Link to Slack conversation for more context - https://pulumi.slack.com/archives/CJUCSNNNS/p1564586818006700.

**Comment by justinvp** [comment]
Allowing the use of `pulumi.getStack()` is relatively easy, but I'd have to investigate further to see what would be involved to enable data sources and `.get(...)`'s. The latter will likely not fit in this milestone.
