### ISSUE TITLE
Interaction between --policy-pack and organizational packs is subtle

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-policy#70]
The `--policy-pack` flag that is a part of `up` and `preview` will accept the path of a local policy pack. It is slightly awkward to have updated an applied policy pack, use it with `--policy-pack`, and then _also_ have the applied version run as well. At the very least, all the rule validations are duplicated, and some might even mismatch.

Would a better idea be to "turn off" the applied version in this case? cc @clstokes @ekrengel

**Comment by ekrengel** [comment]
Is this still an open issue? I think we have decided we need to run both, correct? I think this be solved by https://github.com/pulumi/pulumi-policy/issues/69

**Comment by gpduck** [comment]
Would it make sense to have a separate separate policy command just for running a stack through a local policy?

`pulumi policy preview --policy-pack=../policies`
