### ISSUE TITLE
Expose resource provider configuration for policies

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#78]
Policy users will want to develop policies to check a resource's provider - e.g. `require this resource to be in us-east-1`. We should expose the provider information from the resource to enable this.

**Comment by joeduffy** [comment]
More generally, it seems we should enable the full programming model, with a few exceptions.

These should be legal

- Current project/stack names
- Provider configuration
- Resource provider data sources
- StackReferences

While these likely should not

- Allocating new resources
- Exporting stack outputs

**Comment by joeduffy** [comment]
Attempting to use `getProject` inside of a policy leads to an error:

```
TypeError: pulumi.getProject is not a function
    at /Users/joeduffy/temp/iam-analyzer-policy/index.ts:22:44
    at Generator.next (<anonymous>)
    at /Users/joeduffy/temp/iam-analyzer-policy/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/joeduffy/temp/iam-analyzer-policy/index.ts:4:12)
    at Object.validateStack (/Users/joeduffy/temp/iam-analyzer-policy/index.ts:12:108)
    at Object.<anonymous> (/Users/joeduffy/temp/iam-analyzer-policy/node_modules/@pulumi/policy/server.js:204:49)
    at Generator.next (<anonymous>)
    at /Users/joeduffy/temp/iam-analyzer-policy/node_modules/@pulumi/policy/server.js:21:71
```

**Comment by justinvp** [comment]
Related to #42

**Comment by justinvp** [comment]
> `pulumi.getProject is not a function`

Even when we make the necessary data available to the policy pack program, the reason it's saying `getProject` is not a function, is because inside `@pulumi/pulumi`, when we import the `./metadata` module in `index.ts` to export the `getProject` and `getStack` functions, the `/.metadata` module returned is empty. This is indicative of circular references in our modules (node is returning an empty module to avoid infinite loop). It doesn't happen when accessed from a Pulumi program, but is happening when accessed from a Policy Pack program. Will need to unravel some (ideally all) of our circular dependencies to make this work.

Using the [`madge`](https://www.npmjs.com/package/madge) tool inside the `sdk/nodejs` dir in `pulumi/pulumi` repo yields:

```sh
$ madge -c .
Processed 179 files (1.6s) (6 warnings)

✖ Found 16 circular dependencies!

1) bin/runtime/index.js > bin/runtime/closure/codePaths.js > bin/index.js > bin/config.js > bin/metadata.js
2) bin/output.js > bin/resource.js
3) bin/runtime/index.js > bin/runtime/closure/codePaths.js > bin/index.js > bin/config.js > bin/output.js > bin/resource.js
4) bin/log/index.js > bin/runtime/settings.js > bin/runtime/debuggable.js
5) bin/output.js > bin/resource.js > bin/runtime/resource.js
6) bin/resource.js > bin/runtime/resource.js
7) bin/config.js > bin/output.js > bin/resource.js > bin/runtime/resource.js > bin/runtime/invoke.js
8) bin/output.js > bin/resource.js > bin/runtime/resource.js > bin/runtime/invoke.js
9) bin/resource.js > bin/runtime/resource.js > bin/runtime/invoke.js
10) bin/output.js > bin/resource.js > bin/runtime/resource.js > bin/runtime/invoke.js > bin/runtime/rpc.js
11) bin/resource.js > bin/runtime/resource.js > bin/runtime/invoke.js > bin/runtime/rpc.js
12) bin/runtime/index.js > bin/runtime/closure/codePaths.js > bin/index.js > bin/config.js > bin/output.js
13) bin/runtime/index.js > bin/runtime/closure/codePaths.js > bin/index.js > bin/config.js
14) bin/runtime/index.js > bin/runtime/closure/codePaths.js > bin/index.js > bin/dynamic/index.js
15) bin/runtime/index.js > bin/runtime/closure/codePaths.js > bin/index.js
16) bin/cmd/run/index.js > bin/cmd/run/run.js
```

**Comment by justinvp** [comment]
I looked at the order that `@pulumi/pulumi` modules were being used by a Pulumi program vs. Policy Pack, and there was a difference:

| Program                             | Policy Pack                         |
|-------------------------------------|-------------------------------------|
| cmd/run/index.js                    | cmd/run-policy-pack/index.js        |
| runtime/closure/v8Hooks.js          | runtime/closure/v8Hooks.js          |
| cmd/run/run.js                      | cmd/run-policy-pack/run.js          |
| errors.js                           | errors.js                           |
| utils.js                            | utils.js                            |
| log/index.js                        | log/index.js                        |
| runtime/settings.js                 | runtime/settings.js                 |
| runtime/debuggable.js               | runtime/debuggable.js               |
| runtime/index.js                    | runtime/stack.js                    |
| runtime/closure/serializeClosure.js | asset/index.js                      |
| index.js                            | asset/archive.js                    |
| config.js                           | asset/asset.js                      |
| metadata.js                         | metadata.js                         |
| output.js                           | runtime/index.js                    |
| resource.js                         | runtime/closure/serializeClosure.js |
| runtime/resource.js                 | index.js                            |
| runtime/invoke.js                   | config.js                           |
| asset/index.js                      | output.js                           |
| asset/archive.js                    | resource.js                         |
| asset/asset.js                      | runtime/resource.js                 |
| runtime/rpc.js                      | runtime/invoke.js                   |
| runtime/asyncIterableUtil.js        | runtime/rpc.js                      |
| stackReference.js                   | runtime/asyncIterableUtil.js        |
| dynamic/index.js                    | stackReference.js                   |
| iterable/index.js                   | dynamic/index.js                    |
| runtime/closure/createClosure.js    | iterable/index.js                   |
| runtime/closure/parseFunction.js    | runtime/closure/createClosure.js    |
| runtime/closure/utils.js            | runtime/closure/parseFunction.js    |
| runtime/closure/rewriteSuper.js     | runtime/closure/utils.js            |
| runtime/closure/v8.js               | runtime/closure/rewriteSuper.js     |
| runtime/closure/v8_v10andLower.js   | runtime/closure/v8.js               |
| runtime/closure/v8_v11andHigher.js  | runtime/closure/v8_v10andLower.js   |
| runtime/closure/codePaths.js        | runtime/closure/v8_v11andHigher.js  |
| runtime/config.js                   | runtime/closure/codePaths.js        |
| runtime/stack.js                    | runtime/config.js                   |

I found that tweaking the imports in `cmd/run-policy-pack/index.ts` to match the imports in `cmd/run/index.ts` resolves the issue.

Specifically, changing [these lines](https://github.com/pulumi/pulumi/blob/7b3ec744f467f0ecea7d3ab8cfc0df6e39dbd9f1/sdk/nodejs/cmd/run-policy-pack/run.ts#L21-L22):

```typescript
import { disconnectSync } from "../../runtime/settings";
import { runInPulumiStack } from "../../runtime/stack";
```

To this:

```typescript
import * as runtime from "../../runtime";
```

Results in the modules being loaded in the same order for policy packs as programs, and the `getProject` and `getStack` functions are now available and working as expected in policy packs.

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi/pull/3612 exposes configuration, getStack, getProject, and isDryRun. There are some other remaining things like Resource provider data sources and StackReferences that still need to be exposed.
