### ISSUE TITLE
Allow rules to have categories

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#86]
It would be great if rules could have additional metadata associated with them. Most notably, we should let them have categories, like Compliance, Security, Reliability, Cost, and Performance. This is pretty standard for static analysis tools and will let us provide rich reporting capabilities which, given some future plans, will be important.

It would be good to add this soon so we don't build up a big backlog of unclassified rules. That said, I do assume this would be optional.

**Comment by hausdorff** [comment]
cc @ekrengel—I believe this feature is not slated for "soon", is it?

**Comment by ekrengel** [comment]
This is not slated for "soon", but definitely should be on our roadmap.

**Comment by ekrengel** [comment]
Will open a new issue in services. No milestone commitment

**Comment by ekrengel** [comment]
Closing in favor of https://github.com/pulumi/pulumi-service/issues/4078 since the SDK already supports this
