### ISSUE TITLE
--policy-pack should be guarded by PULUMI_DEBUG_COMMANDS

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#89]
I'm not sure if it was intentional, but the `--policy-pack` flag shows when you do a `pulumi up --help`. I assume we want to not advertise that yet for the same reasons we don't advertise the `policy` command, and instead want to guard it by `PULUMI_DEBUG_COMMANDS`?

**Comment by hausdorff** [comment]
Not on purpose. Let's get this in before v1 release.
