### ISSUE TITLE
Design SDK for Enabling policy pack configuration at application time

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#91]
Many useful policies require parameterization. For example, ensuring that S3 buckets are restricted to VPCs, IAM roles, or IP addresses provided when that rule is applied to an organization. Or ensuring that S3 buckets are encrypted by an organization's KMS key. Etc.

We should make it easy to express policies that have configurable parameters, and then expose the ability to supply these settings when a pack is applied to an organization.

Note that it's likely some of these would need to be supplied dynamically (although it seems fine to scope that into a separate add-on feature). For example, my KMS key might actually be a StackReference to a key defined elsewhere, and making that nice and easy to keep up to date would be great to think about.

**Comment by hausdorff** [comment]
Strong +1. The MVP was strictly scoped at making it possible to write custom policies. But, having written lots and lots of policies, this is probably my first or second most-wished-for feature.

cc @clstokes @ekrengel thoughts?

**Comment by ekrengel** [comment]
Yeah I think this will be a super nice feature, but definitely will require a decent amount of work. I think after this milestone we need to take a step back and look at our backlog to see where this can fit in.

**Comment by clstokes** [comment]
Sounds great, but I think this will need a good bit of design thought to make sure we build something that's manageable and easy to reason about - e.g. ensuring the user knows how their rules will execute when logic/config values are spread across multiple locations.

**Comment by ekrengel** [comment]
> ensuring the user knows how their rules will execute when logic/config values are spread across multiple locations.

@clstokes would love to hear more about what youre envisioning / mean.

**Comment by clstokes** [comment]
@ekrengel If we're "merging" rules defined in a policy pack (that might have default configuration values?) with configuration values that's defined elsewhere (the group? the stack?) to execute rules, we should make it obvious to the user what were the "materialized" rules and configuration values. I think this will require some extra messaging during policy execution about what groups, packs, rules, configuration values, etc. are in use.

**Comment by ekrengel** [comment]
REpurposing this issue for: Design SDK for Enabling policy pack configuration at application time

We will open many other small issues related to this, so that its a manageable size of work.

**Comment by justinvp** [comment]
Closing this since the design is complete! Will be opening smaller issues to track implementation work for next milestone.
