### ISSUE TITLE
Make pulumi.queryable.Resolved public

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#92]
I have a structure that contains `Input<T>`s, which I want to transform into a plain data structure that represents the resolved form. In my case, it's because I want to use some of the AWS IAM policy document structures described here: https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/iam/documents.ts.

I believe the `queryable.ResolvedResource<T>` type defined in `@pulumi/pulumi` is the way to do this, but it doesn't work, because it requires that `T` is a `Resource` (which `PolicyDocument` is not). Poking around in there, it appears `queryable.Resolved<T>` is what I want? Unfortunately it isn't exported from the module.

**Comment by hausdorff** [comment]
We actually need to transition away from `Resolved` and towards something that unwraps the `Input` shapes—`Resolved` on the `CustomResource` types (among other things) does not fully capture nullable fields, and it includes output-only fields that will never be populated in an update. We didn't get to this before we had to switch to v1 work, but it's certainly on the list.

I thought we had an issue for this, but—somehow there isn't? I'll file one.

**Comment by hausdorff** [comment]
Let's fix this this week.

**Comment by hausdorff** [comment]
Let's split out the "transition from resolved" issue. See here: https://github.com/pulumi/pulumi-policy/issues/116
