### ISSUE TITLE
Assertion errors seem incorrect

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#93]
If I have a rule that says this:

```typescript
typedRule(aws.s3.Bucket.isInstance, b => {
    assert.notEqual(b.acl, "public-read");
});
```

and it fails, I see this confusing (and wrong?) error message

```typescript
aws:s3:Bucket (my-bucket):
    mandatory: s3/bucket-public-read-prohibited
    expected 'public-read', got 'public-read'
```

Note that last line.

If I just do a normal Node.js `assert.notEqual("public-read", "public-read")`, I see this:

```
AssertionError [ERR_ASSERTION]: 'public-read' != 'public-read'
```

which makes more sense. Are we misinterpreting the fields on the thrown `AssertionError` object?

**Comment by hausdorff** [comment]
This message is rendered [here](https://github.com/pulumi/pulumi-policy/blob/master/sdk/nodejs/policy/server.ts#L137), which (slightly abbreviated) looks like:

```typescript
                        } else if (e instanceof AssertionError) {
                            [...]
                            expectation = `expected '${e.expected}', got '${e.actual}'`;
                            [...]
                        }
```

Looking now, apparently there is also `e.operator`, which is where the `!=` would come from in that message. :) Oops!

**Comment by hausdorff** [comment]
This is to say: we originally thought that `e.expected` and `e.actual` were all we needed to render a useful message, but apparently we also need `e.operator`. Live and learn.
